import fs from "node:fs";
import path from "node:path";
import { isDataModel } from "@zenstackhq/language/ast";
import type { CliGeneratorContext, CliPlugin } from "@zenstackhq/sdk";

/**
 * Options for the `zenstack-filter/plugin` provider.
 *
 * ```zmodel
 * plugin filter {
 *   provider    = 'zenstack-filter/plugin'
 *   output      = './generated/filter.zmodel'   // default: filter.zmodel next to the schema
 *   filterModel = 'Filter'                       // default: Filter
 *   viewModel   = 'FilterView'                   // default: FilterView
 * }
 * ```
 */
interface FilterPluginOptions {
  /** Where to write the generated ZModel file. Relative paths resolve against the schema's directory. */
  output?: string;
  /** Name of the generated filter model. Default: `Filter`. */
  filterModel?: string;
  /** Name of the generated filter-view model. Default: `FilterView`. */
  viewModel?: string;
}

/**
 * Renders the scaffold for the two persistence models the `useFilter` /
 * `useFilterViews` hooks read and write. The package owns the core columns
 * (`filterSet`, `identifier`, `operator`, `value`, `viewId`, timestamps); the
 * file is written once and is yours to extend afterwards.
 */
function renderModels(filterModel: string, viewModel: string): string {
  return `// Generated by zenstack-filter. This file is written only once — regeneration
// is skipped while these models exist, so you can extend them freely below
// (add scope fields like userId/organizationId, tighten the access policy, …).
// See https://github.com/klyecony/zenstack-filter#required-schema

model ${filterModel} {
  id         String       @id @default(cuid())

  filterSet  String
  identifier String
  operator   String
  value      Json
  viewId     String?
  view       ${viewModel}? @relation(fields: [viewId], references: [id], onDelete: Cascade)

  createdAt  DateTime     @default(now())
  updatedAt  DateTime     @updatedAt

  // Add scope fields here (e.g. userId, organizationId) and fold them into the
  // @@unique below so one owner's filters cannot collide with another's.
  @@unique([filterSet, identifier, viewId])
  @@index([viewId])

  // TODO: restrict access for your app, e.g.
  // @@allow('read,create,update,delete', auth() != null && userId == auth().userId)
  @@allow('all', true)
}

model ${viewModel} {
  id         String       @id @default(cuid())

  name       String
  filterSet  String
  filters    ${filterModel}[]

  createdAt  DateTime     @default(now())
  updatedAt  DateTime     @updatedAt

  // Add the same scope fields as on ${filterModel} and fold them into @@unique.
  @@unique([filterSet, name])

  // TODO: restrict access for your app.
  @@allow('all', true)
}
`;
}

function resolveOutput(context: CliGeneratorContext, output: string | undefined): string {
  const schemaDir = path.dirname(path.resolve(context.schemaFile));
  return path.resolve(schemaDir, output ?? "filter.zmodel");
}

async function generate(context: CliGeneratorContext): Promise<void> {
  const options = (context.pluginOptions ?? {}) as FilterPluginOptions;
  const filterModel = options.filterModel ?? "Filter";
  const viewModel = options.viewModel ?? "FilterView";

  // Never overwrite an existing definition: if either model already lives in
  // the parsed schema, the user has scaffolded (or hand-written) them — skip.
  const declared = new Set(
    context.model.declarations.filter(isDataModel).map(declaration => declaration.name),
  );
  if (declared.has(filterModel) || declared.has(viewModel)) {
    return;
  }

  const outputPath = resolveOutput(context, options.output);
  // Already generated once (but not yet imported) — leave the user's file alone.
  if (fs.existsSync(outputPath)) {
    return;
  }

  fs.mkdirSync(path.dirname(outputPath), { recursive: true });
  fs.writeFileSync(outputPath, renderModels(filterModel, viewModel), "utf8");
}

const plugin: CliPlugin = {
  name: "ZenStack Filter",
  statusText: "Generating filter persistence models",
  generate,
};

export default plugin;
